// <auto-generated />
namespace CampaignMaker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addedAdventureID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedAdventureID));
        
        string IMigrationMetadata.Id
        {
            get { return "201502121748259_addedAdventureID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
